export interface FailureScenario {
  id: string;
  scenario: string;
  trigger: string;
  expectedBehavior: string;
  badBehavior: string;
  fix: string;
  userMessage: string;
  confidenceImpact: string;
  testCase: string;
}

export const failureScenarios: FailureScenario[] = [
  {
    id: 'FS-01',
    scenario: 'DOM Mutation: Review List',
    trigger: 'Amazon changes .review-list to .cr-review-list',
    expectedBehavior: 'Detect structure change, log error, fallback to visual heuristics',
    badBehavior: 'Empty review array returned (Silent Failure)',
    fix: 'Update CSS selector library; Implement automatic structure diffing',
    userMessage: "We're updating our connection to the platform. Please check back in a few minutes.",
    confidenceImpact: '-100% (Block)',
    testCase: 'test_dom_structure_amazon_v2',
  },
  {
    id: 'FS-02',
    scenario: 'Rate Limit: 429 Error',
    trigger: 'Scraper hits IP-based threshold on Walmart',
    expectedBehavior: 'Rotate proxy immediately, exponential backoff',
    badBehavior: '0 reviews found; engine assumes product has no reviews',
    fix: 'Implement ProxyRotator with sticky sessions for individual URLs',
    userMessage: 'Analysis is taking longer than usual due to high traffic.',
    confidenceImpact: '-10% (Latency)',
    testCase: 'test_rate_limit_handling',
  },
  {
    id: 'FS-03',
    scenario: 'Lazy Load: Infinite Scroll',
    trigger: 'Target site only loads reviews on scroll',
    expectedBehavior: 'Execute scroll actions to fetch at least 3 pages',
    badBehavior: 'Only top 3 reviews analyzed; skewed verdict',
    fix: 'Ensure Puppeteer/Playwright script includes scroll_to_bottom loop',
    userMessage: 'Analyzing full review history...',
    confidenceImpact: '-50% (Sample)',
    testCase: 'test_lazy_load_depth',
  },
  {
    id: 'FS-04',
    scenario: 'Captcha: Shadow Block',
    trigger: 'Platform serves a hCaptcha to the scraper',
    expectedBehavior: 'Detect captcha, rotate proxy, or switch to API-based extraction',
    badBehavior: 'Scraper times out or parses captcha page as product data',
    fix: 'Implement CaptchaDetector middleware; switch to "Residential" IP tier',
    userMessage: 'Platform security is high. We are trying an alternative path.',
    confidenceImpact: '-100% (Unknown)',
    testCase: 'test_captcha_detection',
  },
  {
    id: 'FS-05',
    scenario: 'Missing Price Metadata',
    trigger: 'Product is out of stock; price element is null',
    expectedBehavior: 'Analysis continues with null price; scoring skips "Value" metric',
    badBehavior: 'Engine crashes on null reference',
    fix: 'Add optional chaining and default values for all metadata extraction',
    userMessage: 'Analysis complete (Price data unavailable).',
    confidenceImpact: '-5% (Accuracy)',
    testCase: 'test_metadata_null_safety',
  },
  {
    id: 'FS-06',
    scenario: 'Shadow DOM: Reviews',
    trigger: 'Platform wraps reviews in a Shadow Root',
    expectedBehavior: 'Use shadow-root traversal to find elements',
    badBehavior: 'Scraper sees 0 reviews',
    fix: 'Update selectors to use >>> or recursive shadow-piercing logic',
    userMessage: 'Connecting to platform data...',
    confidenceImpact: '-100% (Block)',
    testCase: 'test_shadow_dom_piercing',
  },
  {
    id: 'FS-07',
    scenario: 'Variant Splitting',
    trigger: "URL for 'Blue' shoes only shows 'Blue' reviews",
    expectedBehavior: "Detect variant param; prompt user to check 'All Variants'",
    badBehavior: 'Skewed confidence based on low-volume variant',
    fix: 'Auto-redirect to /all_reviews endpoint if available',
    userMessage: 'Note: This analysis is specific to the selected variant.',
    confidenceImpact: '-20% (Context)',
    testCase: 'test_variant_isolation',
  },
  {
    id: 'FS-08',
    scenario: 'Redirect Loop: Region Lock',
    trigger: '.com URL redirects to .co.uk based on proxy',
    expectedBehavior: 'Stick to the user-provided region; ensure local currency',
    badBehavior: 'Scraper pulls UK data for US user; price conversion error',
    fix: 'Map proxy region to target URL TLD',
    userMessage: 'Adjusting for your region...',
    confidenceImpact: '-15% (Relevance)',
    testCase: 'test_regional_consistency',
  },
  {
    id: 'FS-09',
    scenario: 'Malformed HTML: Unclosed Tags',
    trigger: 'Listing page has broken HTML syntax',
    expectedBehavior: 'Use resilient parser (Cheerio/BeautifulSoup)',
    badBehavior: 'Parser fails; partial data return',
    fix: 'Enforce strict HTML sanitization before parsing',
    userMessage: 'Parsing product data...',
    confidenceImpact: '-10% (Data)',
    testCase: 'test_html_resilience',
  },
  {
    id: 'FS-10',
    scenario: 'Edge Product: Service/Digital',
    trigger: 'User pastes a link to a digital subscription',
    expectedBehavior: 'Identify as "Non-Physical"; adjust scoring for digital signals',
    badBehavior: 'Scraper looks for "shipping" or "packaging" keywords',
    fix: 'Category detection logic to flag non-physical goods',
    userMessage: 'Note: Digital products have different trust patterns.',
    confidenceImpact: '-30% (Scoring)',
    testCase: 'test_digital_good_detection',
  },
  {
    id: 'FS-11',
    scenario: 'Bimodal Sentiment Spike',
    trigger: '100x 5-star and 100x 1-star reviews on same day',
    expectedBehavior: 'Flag as "Review War"; return CAUTION',
    badBehavior: 'Engine averages to 3 stars; returns "Normal"',
    fix: 'Implement SentimentVolatility check; flag high-variance bursts',
    userMessage: 'Caution: High conflict detected in recent reviews.',
    confidenceImpact: '-60% (Trust)',
    testCase: 'test_sentiment_volatility',
  },
  {
    id: 'FS-12',
    scenario: 'Proxy Leak: Internal IP',
    trigger: 'Scraper header leaks internal server IP',
    expectedBehavior: 'Scrub headers; use anonymous rotation',
    badBehavior: 'Platform bans the entire server range',
    fix: 'Hardened header middleware (User-Agent randomizer, Referer spoofing)',
    userMessage: 'Connection refresh in progress...',
    confidenceImpact: '-100% (Block)',
    testCase: 'test_header_anonymity',
  },
  {
    id: 'FS-13',
    scenario: 'JSON-LD Schema Change',
    trigger: 'Platform moves metadata from HTML to Script tag',
    expectedBehavior: 'Update extractor to prioritize JSON-LD over DOM',
    badBehavior: '0 metadata found (Price, Rating, Author)',
    fix: 'Implement SchemaPrioritizer to check script tags first',
    userMessage: 'Updating metadata engine...',
    confidenceImpact: '-5% (Minor)',
    testCase: 'test_json_ld_extraction',
  },
  {
    id: 'FS-14',
    scenario: 'Incentivized: Hidden Badge',
    trigger: '"Vine Voice" or "Free Sample" badge is an SVG icon',
    expectedBehavior: 'Use aria-label or image-alt detection',
    badBehavior: 'Incentivized reviews treated as organic',
    fix: 'Map all incentivized icon classes/alt-texts to signal engine',
    userMessage: 'Detected incentivized review patterns.',
    confidenceImpact: '-40% (Weight)',
    testCase: 'test_incentivized_detection',
  },
  {
    id: 'FS-15',
    scenario: 'Review Body: Image-Only',
    trigger: 'Reviews contain photos but no text',
    expectedBehavior: 'Analyze image count; use as "Trust Signal"',
    badBehavior: '0 text found; engine marks as "Empty/Suspicious"',
    fix: 'Implement MediaDensity signal; higher trust for user photos',
    userMessage: 'Analysis includes media verification.',
    confidenceImpact: '+15% (Safe)',
    testCase: 'test_media_only_reviews',
  },
  {
    id: 'FS-16',
    scenario: 'Rate Limit: 403 Forbidden',
    trigger: 'WAF (Web App Firewall) blocks the request',
    expectedBehavior: 'Switch IP geoloc; reduce concurrency',
    badBehavior: 'Analysis hangs or returns "Error"',
    fix: 'Implement RetryManager with circuit breaker pattern',
    userMessage: 'Taking a quick breath to bypass congestion.',
    confidenceImpact: '-100% (Block)',
    testCase: 'test_waf_bypass',
  },
  {
    id: 'FS-17',
    scenario: 'Dynamic ID Selectors',
    trigger: 'Platform uses random classes (e.g., .css-1x8a2)',
    expectedBehavior: 'Use data-attributes or positional selectors',
    badBehavior: 'Scrapers break on every build',
    fix: 'Use data-testid or stable parent/child relationships',
    userMessage: 'Scanning structure...',
    confidenceImpact: '-100% (Maintenance)',
    testCase: 'test_stable_selectors',
  },
  {
    id: 'FS-18',
    scenario: 'Content Security Policy (CSP)',
    trigger: 'JS-heavy site prevents external script execution',
    expectedBehavior: 'Use pure HTML/Cheerio fallback where possible',
    badBehavior: 'Engine fails to execute logic on-page',
    fix: 'Server-side rendering (SSR) of the scraped page',
    userMessage: 'Rendering product view...',
    confidenceImpact: '-20% (Speed)',
    testCase: 'test_csp_resilience',
  },
  {
    id: 'FS-19',
    scenario: 'Translation Failure',
    trigger: 'Auto-translating non-English reviews fails',
    expectedBehavior: 'Detect language; flag as "Foreign Pattern"',
    badBehavior: 'Gibberish text analyzed as suspicious',
    fix: 'Use localized sentiment models or pass-through for trusted regions',
    userMessage: 'Note: Non-English reviews were analyzed.',
    confidenceImpact: '-15% (Context)',
    testCase: 'test_multilingual_analysis',
  },
  {
    id: 'FS-20',
    scenario: 'Missing Reviewer ID',
    trigger: 'Anonymous reviews (no unique ID)',
    expectedBehavior: 'Group by "Anonymous" bucket; increase suspicion',
    badBehavior: 'Engine crashes on unique key constraint',
    fix: 'Allow null/anonymous keys; flag as High_Anonymity signal',
    userMessage: 'Caution: High percentage of anonymous feedback.',
    confidenceImpact: '-25% (Suspicion)',
    testCase: 'test_anonymous_reviewer_handling',
  },
  {
    id: 'FS-21',
    scenario: 'Reviewer Profile Blocked',
    trigger: 'Platform hides reviewer history',
    expectedBehavior: 'Score based on profile visibility ratio',
    badBehavior: 'engine assumes 0 history for all',
    fix: 'Flag Profile_Opacity as a signal; ratio of hidden to public',
    userMessage: 'Limited reviewer history available.',
    confidenceImpact: '-10% (Detail)',
    testCase: 'test_profile_visibility',
  },
  {
    id: 'FS-22',
    scenario: 'Timezone Drift',
    trigger: '"2 hours ago" parsed incorrectly',
    expectedBehavior: 'Use server-time relative to scraping time',
    badBehavior: 'Review dates are off by years',
    fix: 'Normalize all relative dates to ISO timestamps',
    userMessage: 'Normalizing time signals...',
    confidenceImpact: '-5% (Temporal)',
    testCase: 'test_date_normalization',
  },
  {
    id: 'FS-23',
    scenario: 'Review Update: Negative to Positive',
    trigger: 'Review body says "Seller fixed it"',
    expectedBehavior: 'Detect "Seller-Influenced" pattern',
    badBehavior: 'Weighted as a pure positive review',
    fix: 'NLP check for "customer service", "replacement", "fixed"',
    userMessage: 'Signal: Seller-resolved issue detected.',
    confidenceImpact: '-5% (Mixed)',
    testCase: 'test_updated_review_logic',
  },
  {
    id: 'FS-24',
    scenario: 'Overlapping ASINs',
    trigger: 'Listing page shows reviews for 5 different products',
    expectedBehavior: "Extract 'Review For' metadata if available",
    badBehavior: 'High noise; score is meaningless',
    fix: "Filter reviews by current product variant ID",
    userMessage: 'Filtering reviews for this specific model.',
    confidenceImpact: '-30% (Noise)',
    testCase: 'test_asin_filtering',
  },
  {
    id: 'FS-25',
    scenario: 'Bot-Trap: Invisible Reviews',
    trigger: 'Platform embeds honey-pot reviews for bots',
    expectedBehavior: 'Filter reviews by visibility (CSS: display:none)',
    badBehavior: 'Engine picks up fake "positive" reviews',
    fix: 'Ensure scraper only picks up visible, human-readable text',
    userMessage: 'Filtering noise...',
    confidenceImpact: '-50% (Accuracy)',
    testCase: 'test_honeypot_avoidance',
  },
  {
    id: 'FS-26',
    scenario: 'Truncated Reviews',
    trigger: '"Read more" button hides 80% of text',
    expectedBehavior: 'Trigger click/expand or use API endpoint',
    badBehavior: 'Short-text analysis results in "Safe" but misses red flags',
    fix: 'Prefer "raw" data endpoints over DOM scraping where possible',
    userMessage: 'Expanding full review text...',
    confidenceImpact: '-40% (Depth)',
    testCase: 'test_text_expansion',
  },
  {
    id: 'FS-27',
    scenario: 'Inconsistent Star-to-Text',
    trigger: '5-star rating with "worst product ever" text',
    expectedBehavior: 'NLP sentiment check must override numeric rating',
    badBehavior: 'Marked as "Positive"',
    fix: 'Cross-validate numeric rating vs text sentiment score',
    userMessage: 'Detected rating-to-text discrepancy.',
    confidenceImpact: '-35% (Suspicion)',
    testCase: 'test_sentiment_mismatch',
  },
  {
    id: 'FS-28',
    scenario: 'Bot-Burst: Temporal Clumping',
    trigger: '20 reviews in 2 seconds, then 0',
    expectedBehavior: 'Temporal signal analysis',
    badBehavior: 'Marked as "Trending"',
    fix: 'Flag as Synthetic_Burst if variance < 1 second',
    userMessage: 'Caution: Synthetic review burst detected.',
    confidenceImpact: '-80% (Trust)',
    testCase: 'test_temporal_clumping',
  },
  {
    id: 'FS-29',
    scenario: 'Bot-Body: Markov Chain',
    trigger: 'Text is grammatically correct but nonsensical',
    expectedBehavior: 'Linguistic entropy analysis',
    badBehavior: 'Marked as "Normal"',
    fix: 'Measure Word_Probability; flag low-entropy repetitive text',
    userMessage: 'Pattern: Automated text generation detected.',
    confidenceImpact: '-70% (Trust)',
    testCase: 'test_linguistic_entropy',
  },
  {
    id: 'FS-30',
    scenario: 'Reviewer: Professional Reviewer',
    trigger: 'History shows 500 reviews, all 5-star',
    expectedBehavior: 'Profile history analysis',
    badBehavior: 'Marked as "Trusted User"',
    fix: 'Flag as Incentivized_History if positive ratio > 98%',
    userMessage: 'Caution: High-volume positive reviewer history.',
    confidenceImpact: '-30% (Weight)',
    testCase: 'test_reviewer_history_audit',
  },
  {
    id: 'FS-31',
    scenario: 'Category Drift: Shoes to Tech',
    trigger: 'Listing was originally for shoes, now a charger',
    expectedBehavior: 'Compare review category to metadata category',
    badBehavior: 'High trust from old "shoe" reviews',
    fix: 'Check Category_Consistency over time',
    userMessage: 'Warning: Listing history shows category change.',
    confidenceImpact: '-90% (Avoid)',
    testCase: 'test_category_consistency',
  },
  {
    id: 'FS-32',
    scenario: 'Reviewer: Geo-Impossibility',
    trigger: 'User reviews US product, then UK, then AU in 1h',
    expectedBehavior: 'Geo-temporal check',
    badBehavior: 'Marked as "Global User"',
    fix: 'Flag Impossible_Travel in reviewer profiles',
    userMessage: 'Signal: Suspicious reviewer location patterns.',
    confidenceImpact: '-40% (Weight)',
    testCase: 'test_geo_impossible_travel',
  },
  {
    id: 'FS-33',
    scenario: 'Empty Page: 200 OK',
    trigger: 'Platform returns 200 but page is "Out of Stock"',
    expectedBehavior: 'Detect "Out of Stock" UI',
    badBehavior: 'engine assumes 0 reviews',
    fix: 'Log as "Status: Inactive"; retry with different proxy',
    userMessage: 'Product is currently unavailable for analysis.',
    confidenceImpact: '-100% (Unknown)',
    testCase: 'test_empty_page_handling',
  },
  {
    id: 'FS-34',
    scenario: 'Abuse of "Helpful" Vote',
    trigger: '1-star review with 5000 "helpful" votes',
    expectedBehavior: 'Vote-to-Volume ratio check',
    badBehavior: 'marked as "Most Important"',
    fix: 'Flag as Vote_Manipulation if votes > 10% of total reviews',
    userMessage: 'Caution: Suspicious vote patterns detected.',
    confidenceImpact: '-20% (Weight)',
    testCase: 'test_vote_manipulation',
  },
  {
    id: 'FS-35',
    scenario: 'Hidden Reviews: "See all"',
    trigger: 'Listing only shows 10/1000 reviews',
    expectedBehavior: 'Navigate to full list',
    badBehavior: 'only 10 analyzed',
    fix: 'Ensure scraper visits /product-reviews/ sub-page',
    userMessage: 'Analyzing total feedback pool...',
    confidenceImpact: '-60% (Sample)',
    testCase: 'test_pagination_depth',
  },
  {
    id: 'FS-36',
    scenario: 'Malformed Price: Range',
    trigger: 'Price shows "$10 - $100"',
    expectedBehavior: 'Parse as range; take midpoint or specific variant',
    badBehavior: 'Engine crashes on string-to-number',
    fix: 'Implement RangeParser for pricing metadata',
    userMessage: 'Adjusting for price variants...',
    confidenceImpact: '-5% (Metadata)',
    testCase: 'test_price_range_parsing',
  },
  {
    id: 'FS-37',
    scenario: 'Bot-Pattern: Unique ID suffix',
    trigger: 'reviews by "John A.", "John B.", "John C."',
    expectedBehavior: 'Name pattern detection',
    badBehavior: 'Marked as "Safe"',
    fix: 'Flag Sequential_Author_Naming',
    userMessage: 'Caution: Sequential reviewer naming patterns.',
    confidenceImpact: '-35% (Suspicion)',
    testCase: 'test_author_patterns',
  },
  {
    id: 'FS-38',
    scenario: 'Review Body: URL injection',
    trigger: 'Review contains a bit.ly link',
    expectedBehavior: 'Detect and flag Malicious_Link',
    badBehavior: 'Analyzed as normal text',
    fix: 'Filter outbound URLs; weight as -50',
    userMessage: 'Warning: Review contains suspicious links.',
    confidenceImpact: '-50% (Avoid)',
    testCase: 'test_link_injection',
  },
  {
    id: 'FS-39',
    scenario: 'Image: Duplicate Across Listings',
    trigger: 'User photo is found on 10 different products',
    expectedBehavior: 'Image hash comparison (future)',
    badBehavior: 'High trust',
    fix: 'Metadata check for shared image assets',
    userMessage: 'Caution: Duplicate media detected across products.',
    confidenceImpact: '-60% (Trust)',
    testCase: 'test_image_uniqueness',
  },
  {
    id: 'FS-40',
    scenario: 'Reviewer: Zero Day Account',
    trigger: 'Reviewer account created same day as review',
    expectedBehavior: 'Account age check',
    badBehavior: 'Marked as "New User"',
    fix: 'Weight as -20 for high-volume bursts',
    userMessage: 'Note: High volume of new reviewer accounts.',
    confidenceImpact: '-15% (Weight)',
    testCase: 'test_account_age',
  },
  {
    id: 'FS-41',
    scenario: 'Page Structure: Tabbed Reviews',
    trigger: 'Reviews hidden under a "Reviews" tab',
    expectedBehavior: 'Simulate click to reveal',
    badBehavior: '0 reviews found',
    fix: 'Wait for visibility; trigger tab click',
    userMessage: 'Opening review data...',
    confidenceImpact: '-100% (Block)',
    testCase: 'test_tabbed_content',
  },
  {
    id: 'FS-42',
    scenario: 'Language: Sarcasm Detection',
    trigger: '"Great product, if you want a fire!"',
    expectedBehavior: 'NLP sarcasm/irony detection',
    badBehavior: 'Marked as "Positive"',
    fix: 'Invert sentiment if high-weight negative nouns follow',
    userMessage: 'Detected ironic sentiment signals.',
    confidenceImpact: '-40% (Suspicion)',
    testCase: 'test_sarcasm_detection',
  },
  {
    id: 'FS-43',
    scenario: 'Metadata: Reviewer Rank',
    trigger: 'Reviewer is "Top 100 Contributor"',
    expectedBehavior: 'Higher weight to trusted badges',
    badBehavior: 'Same as regular user',
    fix: 'Extract and weight platform-specific badges',
    userMessage: 'High-trust reviewer signals detected.',
    confidenceImpact: '+20% (Safe)',
    testCase: 'test_reviewer_ranking',
  },
  {
    id: 'FS-44',
    scenario: 'Review Body: Length Outlier',
    trigger: 'Review is 10,000 words (copy-paste book)',
    expectedBehavior: 'Truncate and flag Bot_Spam',
    badBehavior: 'Sentiment skew',
    fix: 'Limit analysis to first 1000 words; flag outlier',
    userMessage: 'Filtering spam patterns...',
    confidenceImpact: '-30% (Noise)',
    testCase: 'test_length_outlier',
  },
  {
    id: 'FS-45',
    scenario: 'Regional: Slang Manipulation',
    trigger: 'Use of specific slang to hide bot patterns',
    expectedBehavior: 'Localized slang dictionaries',
    badBehavior: 'Marked as "Nonsense"',
    fix: 'Update linguistic models with common bot-slang',
    userMessage: 'Analyzing localized language patterns.',
    confidenceImpact: '-10% (Detail)',
    testCase: 'test_slang_resilience',
  },
  {
    id: 'FS-46',
    scenario: 'Metadata: "Verified" removal',
    trigger: 'Platform removes verified badge from review',
    expectedBehavior: 'Detect badge removal (diff)',
    badBehavior: 'Engine misses the signal',
    fix: 'Store historical snapshot; flag status change',
    userMessage: 'Warning: Verified status recently changed.',
    confidenceImpact: '-40% (Suspicion)',
    testCase: 'test_verified_status_drift',
  },
  {
    id: 'FS-47',
    scenario: 'Review: Competitive Defamation',
    trigger: '"Brand X is better, buy Brand X instead"',
    expectedBehavior: 'Brand mention extraction',
    badBehavior: 'Weighted as negative for this product',
    fix: 'Flag as Competitive_Promotion',
    userMessage: 'Note: Review promotes a different brand.',
    confidenceImpact: '-15% (Noise)',
    testCase: 'test_competitive_promotion',
  },
  {
    id: 'FS-48',
    scenario: 'Bot-Pattern: All Caps Surge',
    trigger: '20 reviews in ALL CAPS at once',
    expectedBehavior: 'Case analysis',
    badBehavior: 'Marked as "Excited"',
    fix: 'Flag as Case_Anomaly',
    userMessage: 'Caution: Abnormal formatting patterns.',
    confidenceImpact: '-20% (Suspicion)',
    testCase: 'test_case_anomaly',
  },
  {
    id: 'FS-49',
    scenario: 'Scraper: Headless detection',
    trigger: 'navigator.webdriver is true',
    expectedBehavior: 'Use hardened browser fingerprinting',
    badBehavior: 'Platform serves "403" or "Robot" page',
    fix: 'Ensure stealth plugin is active; verify fingerprints',
    userMessage: 'Securing connection...',
    confidenceImpact: '-100% (Block)',
    testCase: 'test_browser_stealth',
  },
  {
    id: 'FS-50',
    scenario: 'Product: Inactive Listing',
    trigger: 'Reviewing a listing with 0 reviews',
    expectedBehavior: 'Return "NEW" or "EMPTY"',
    badBehavior: 'engine crashes on 0-length array',
    fix: 'Graceful exit for zero-data listings',
    userMessage: 'This product has no reviews yet.',
    confidenceImpact: '0% (Neutral)',
    testCase: 'test_zero_review_grace',
  },
];
